/* Generated By:JJTree: Do not edit this line. DivExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class DivExp extends SimpleNode {
  public DivExp(int id) {
    super(id);
  }

  public DivExp(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0b702a60cf0a08fe1b2a73ab974d5031 (do not edit this line) */
