/* Generated By:JJTree: Do not edit this line. FPLitExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class FPLitExp extends SimpleNode {
  public FPLitExp(int id) {
    super(id);
  }

  public FPLitExp(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4fb4d696924423813fc91c2df5f49d08 (do not edit this line) */
