/* Generated By:JJTree: Do not edit this line. IdExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class IdExp extends SimpleNode {
  public IdExp(int id) {
    super(id);
  }

  public IdExp(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3a3cfc9b9e1c90bfb3ebd7b96d67fdf (do not edit this line) */
