/* Generated By:JJTree: Do not edit this line. LetExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class LetExp extends SimpleNode {
  public LetExp(int id) {
    super(id);
  }

  public LetExp(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=77bdf5fe9a47f482aaf4cd6320ffcc24 (do not edit this line) */
