/* Generated By:JJTree: Do not edit this line. Start.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package AST;

public
class Start extends SimpleNode {
  public Start(int id) {
    super(id);
  }

  public Start(CalcParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79076487612a2d87885ebe0c79c3b533 (do not edit this line) */
